info/urls.py
from django.urls import path, include

from . import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'employees', views.EmployeeViewset)



urlpatterns = [
    path('', include(router.urls)),
    path('home', views.my_index, name='my_index_view'),
    path('home/<int:emp_id>', views.my_detailed_view, name='my_detailed_view'),
    path('home/delete/<int:emp_id>', views.delete_view, name='delete_view'),
    path('update_view/<int:emp_id>', views.update_view, name='update_view'),
    path('home/update_form/<int:emp_id>', views.update_form_view, name='update_form_view'),
    path('create_form', views.create_form, name='create_employee_form'),
    path('create_emp', views.create_emp, name='create_emp'),
    # path('end', views.end_page, name='end_page')
]

sampleProject/urls.py
from django.contrib import admin
from django.urls import path, include
from info import urls as info_urls
import rest_framework


urlpatterns = [
    path('info/', include((info_urls, 'info'), namespace='info')),
    # path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
]

info/models.py
from django.db import models

# Create your models here.



class Employee(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=50, null=True, blank=True)
    sal = models.DecimalField(null=True, decimal_places=2, max_digits=10)

    # def __init__(self):
    #     return

    def __str__(self):
        return self.name

info/views.py
from django.shortcuts import render

from django.http import HttpResponse, HttpResponseRedirect
from .models import Employee
from django.urls import reverse
from rest_framework.response import Response
from rest_framework import viewsets
from info.serializers import EmployeeSerializer
from rest_framework.decorators import action
from django.db.models import Max

def my_index(request):
    # return HttpResponse("Welcome to my index page")
    employee_list = Employee.objects.values('id', 'name', 'sal')
    # return render(request, 'info/home.html', context={'employee_details': employee_list})
    return HttpResponse(employee_list)


def my_detailed_view(request, emp_id):
    try:
        employee = Employee.objects.filter(id=emp_id)
        if employee.exists():
            return render(request, 'info/home.html', context={'employee_details': employee})
        raise Exception("Employee not found in the database")
    except Exception as e:
        return render(request, 'info/info.html', context={'info': str(e)})


# def end_page(request):
#     # return HttpResponse("Thank You for visiting my site")
#     return render(request, 'info/end.html')

def create_form(request):
    return render(request, 'info/create_emp.html')

def update_form_view(request, emp_id):
    employee = Employee.objects.filter(id=emp_id).last()
    return render(request, 'info/update_emp.html', context={'employee_details': employee})

def create_emp(request):
    last_emp_id = Employee.objects.last().id
    name = request.POST.get('name', 'emp_name')
    sal = request.POST.get('sal', 'emp_sal')
    emp = Employee.objects.create(name=name, sal=sal, id=last_emp_id+1)
    return HttpResponseRedirect(reverse('info:my_detailed_view', args=(emp.id,)))


def delete_view(request, emp_id):
    Employee.objects.filter(id=emp_id).delete()
    return HttpResponseRedirect(reverse('info:my_index_view'))
    # employee_list = Employee.objects.values('id', 'name', 'sal')
    # return render(request, 'info/home.html', context={'employee_details': employee_list})

def update_view(request, emp_id):
    emp = Employee.objects.filter(id=emp_id).last()
    name = request.POST.get('name', emp.name)
    sal = request.POST.get('sal', emp.sal)
    Employee.objects.filter(id=emp_id).update(name=name, sal=sal)
    # emp.name = name
    # emp.sal = sal
    # emp.save()
    return HttpResponseRedirect(reverse('info:my_detailed_view', args=(emp.id,)))



class EmployeeViewset(viewsets.ModelViewSet):
    queryset = Employee.objects.all()
    serializer_class = EmployeeSerializer
    allowed_methods = ['get', 'post', 'patch', 'delete']


    def list(self, request, *args, **kwargs):
        queryset = self.queryset
        max_sal = Employee.objects.aggregate(Max('sal'))
        max_sal = max_sal['sal__max']
        context = {'max_sal': max_sal}
        serializer = self.get_serializer(queryset, many=True, context=context)
        return Response(serializer.data)
    
    def create(self, request):
        data = request.data
        serializer = self.get_serializer(data=data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.validated_data)
    
    def update(self, request, *args, **kwargs):
        data = request.data
        queryset = self.get_object()
        serializer = self.get_serializer(instance=queryset, data=data, partial=True)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)

    def destroy(self, request, pk=None, *args, **kwargs):
        queryset = self.queryset.filter(id=pk).delete()
        return Response({'detail': 'Object deleted succesfully'})
    
    @action(methods=['get'], detail=False, url_name='increase_sal')
    def increase_sal(self, request, *args, **kwargs):
        queryset = self.queryset
        for obj in queryset:
            obj.sal = 1.1 * float(obj.sal)
            obj.save(update_fields=['sal'])
        queryset = self.queryset
        serializer = self.get_serializer(queryset, many=True)
        return Response(serializer.data)

info/templates/info/create_emp.html
<h3>Create Employee</h3>
<form action="{% url 'info:create_emp' %}" method="post">
    {% csrf_token %}
    <label for="emp_name">Enter Name</label>
    <input type="text" name="name" id="emp_name">
    <br>
    <label for="emp_sal">Enter Salary</label>
    <input type="number" name="sal" id="emp_sal">
    <br>
    <input type="submit" value="submit">
</form>

info/templates/info/end.html
<h1>Thank you for visiting my Page</h1>

info/templates/info/home.html
<a href="http://localhost:7000/info/home">Home</a>
</br>
{% if employee_details %}
    {% for employee in employee_details %}
        <h3><a href='http://localhost:7000/info/home/{{ employee.id }}'>id: {{employee.id}}</a>   <a href='http://localhost:7000/info/home/delete/{{ employee.id }}'>delete</a>   <a href='http://localhost:7000/info/home/update_form/{{ employee.id }}'>update</a></h3>
        <h3>name: {{employee.name}}</h3>
        <h3>sal: {{employee.sal}}</h3>
        </br>
    {% endfor %}
{% else %}
    <h3>No employee details found</h3>
{% endif %}

<a href='http://localhost:7000/info/create_form'>Create New Employee</a>

info/templates/info/info.html
<a href="http://localhost:7000/info/home">Return to Home</a>

<h3>{{ info }}</h3>

info/templates/info/update_emp.html
<h3>Update Employee</h3>
<form action="{% url 'info:update_view' employee_details.id %}" method="post">
    {% csrf_token %}
    <label for="emp_name">Enter Name</label>
    <input type="text" name="name" id="emp_name" value={{employee_details.name}}>
    <br>
    <label for="emp_sal">Enter Salary</label>
    <input type="number" name="sal" id="emp_sal" value={{employee_details.sal}}>
    <br>
    <input type="submit" value="submit">
</form>